on:
  - push
  - workflow_dispatch

name: 1. DEV Environment Build
jobs:
  build_and_deploy:
    name: Build and Deploy
    uses: p6m-dev/github-actions/.github/workflows/build-deploy-maven.yaml@main
    secrets:
      ARTIFACTORY_USERNAME: ${{'{'}}{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_IDENTITY_TOKEN: ${{'{'}}{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}
      UPDATE_MANIFEST_TOKEN: ${{'{'}}{ secrets.UPDATE_MANIFEST_TOKEN }}

  generate_subgraph:
    name: Generate Subgraph
    needs: build_and_deploy
    uses: p6m-dev/github-actions/.github/workflows/generate-subgraph-domain-gateway.yaml@main
    with:
      APPLICATION_IMAGE: p6m-dev.jfrog.io/${{'{'}}{ vars.TF_VAR_JV_PROJECT }}-${{'{'}}{ vars.TF_VAR_JV_NAME }}-docker-local/applications/${{'{'}}{ github.event.repository.name }}-server@${{'{'}}{ needs.build_and_deploy.outputs.digest }}
    secrets:
      SUBGRAPH_PULL_TOKEN: ${{'{'}}{ secrets.SUBGRAPH_PULL_TOKEN }}
      REPOSITORY_PUSH_TOKEN: ${{'{'}}{ secrets.REPOSITORY_PUSH_TOKEN }}
      ARTIFACTORY_USERNAME: ${{'{'}}{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_IDENTITY_TOKEN: ${{'{'}}{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}
      PIPELINE_TRIGGER_TOKEN: ${{'{'}}{ secrets.UPDATE_MANIFEST_TOKEN }}
